spring:
  datasource:
    username: root
    password: 999Iamtinydust
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 47.107.34.224
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.entity
server:
  port: 8080
logging:
  config: classpath:log/logback-spring.xml

