name: 'generate java code by schema'

on:
  push:
    branches:
      - master

jobs:
  generate-java-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
        uses: actions/setup-java@v1
          with:
            java-version: 1.8
    - name: Build with Maven
          run: mvn clean jsonschema2pojo:generate -f pom.xml

