name: 'generate java code by schema'

on:
  push:
    branches:
      - master

jobs:
  generate-java-code:
    runs-on: ubuntu-latest
    steps:
      - name: install maven cli
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-args: jsonschema2pojo:generate -f pom.xml

